name: Docker Image Build and Push

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag nguyennhan1992/gridvllm:latest .

    - name: Login Docker Hub
      run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}

    - name: PUSH to Docker Hub
      run: docker push nguyennhan1992/gridvllm:latest
